name: shazam_vin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  barcode_scan2: ^4.0.0
  http: ^1.1.0
  shared_preferences: ^2.0.8
  google_fonts: ^4.0.5
  material_design_icons_flutter: 7.0.7296
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  fluttertoast: ^8.2.4
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/images/Vin.jpg
    - assets/images/Vigne.jpg

  fonts:
    - family: Roboto

  uses-material-design: true


